### ISSUE TITLE
Errors when trying to run example code

### ISSUE THREAD

**Issue by edbgon** [jath03/openrgb-python#1]
Hi,

I have compiled the latest OpenRGB from gitlab and installed both the git and pip3 versions of openrgb-python and get the following error when trying to run the example code in basics.py.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bobris/.local/lib/python3.8/site-packages/openrgb/network.py", line 61, in listen
    self.callback(device_id, packet_type, utils.ControllerData.unpack(data))
  File "/home/bobris/.local/lib/python3.8/site-packages/openrgb/utils.py", line 426, in unpack
    start, mode = ModeData.unpack(data, start, x)
  File "/home/bobris/.local/lib/python3.8/site-packages/openrgb/utils.py", line 267, in unpack
    start += RGBColor.size
AttributeError: type object 'RGBColor' has no attribute 'size'
```

**Comment by jath03** [comment]
Reinstall from either source and try again.

**Comment by edbgon** [comment]
Sorry for my slow response, I confirm the fix has worked.
