### ISSUE TITLE
OpenRGBClient hangs on Connection

### ISSUE THREAD

**Issue by CDNievas** [jath03/openrgb-python#16]
The code when is exectued on a Raspberry Pi 3 (Python 3.7.3) hangs out in the lock acquire()
The client is connected to the server because it appears on the list of the OpenRGB program...

But when I execute it on another PC with Linux Mint (Python 3.8.5) it works normally... so IDK

Please help! Thx

```bash
Traceback (most recent call last):
  File "app.py", line 24, in <module>
    OpenRGB.connect(IP_OPENRGB,PORT_OPENRGB)
  File "/home/pi/Desktop/deploys/leds-twitch/OpenRGB.py", line 9, in connect
    client = OpenRGBClient(ip, port, '')
  File "/home/pi/.local/lib/python3.7/site-packages/openrgb/orgb.py", line 235, in __init__
    self.comms.requestDeviceNum()
  File "/home/pi/.local/lib/python3.7/site-packages/openrgb/network.py", line 163, in requestDeviceNum
    self.read()
  File "/home/pi/.local/lib/python3.7/site-packages/openrgb/network.py", line 113, in read
    self.callback(device_id, packet_type, buff[0])
  File "/home/pi/.local/lib/python3.7/site-packages/openrgb/orgb.py", line 248, in _callback
    self.comms.requestDeviceData(x)
  File "/home/pi/.local/lib/python3.7/site-packages/openrgb/network.py", line 154, in requestDeviceData
    self.send_header(device, utils.PacketType.REQUEST_CONTROLLER_DATA, struct.calcsize('I'))
  File "/home/pi/.local/lib/python3.7/site-packages/openrgb/network.py", line 176, in send_header
    self.lock.acquire()
  File "/home/pi/.local/lib/python3.7/site-packages/engineio/client.py", line 39, in signal_handler
    return original_signal_handler(sig, frame)
  File "/home/pi/.local/lib/python3.7/site-packages/socketio/client.py", line 26, in signal_handler
    return original_signal_handler(sig, frame)
```

**Comment by jath03** [comment]
What openrgb-python version is on the pi?  I'm pretty sure this is a problem that I fixed in v0.2.4.  If not and you have the newest version, can you show the code that produced the error?

**Comment by CDNievas** [comment]
openrgb-python: 0.2.5

![image](https://user-images.githubusercontent.com/16874674/105044507-94c34300-5a45-11eb-9f58-0078c88e615f.png)

https://github.com/CDNievas/leds-twitch/blob/main/OpenRGB.py
And the code is here. Thanks!

**Comment by jath03** [comment]
Is the server crashing or the connecting getting interrupted?  Unless something is really broken here, the client is just waiting on a response from the server and not getting one.

**Comment by CDNievas** [comment]
I'll check and tell you

**Comment by CDNievas** [comment]
Well I tried again installing directly the last version uploaded to this repository but it didnt work... same error, the client connects to the server but it hangs...

![image](https://user-images.githubusercontent.com/16874674/106333235-f914ac80-6266-11eb-8e5e-af9573175d94.png)

Tried also using another port, and disabling the windows firewall

**Comment by CDNievas** [comment]
Missclick sry

**Comment by CDNievas** [comment]
I'll try running it with docker and another Python version

**Comment by jath03** [comment]
Updating to v0.2.6 should fix this issue.  Lmk how it goes.

**Comment by CDNievas** [comment]
I'll try thx!
