### ISSUE TITLE
"IndexError: list assignment index out of range" when creating OpenRGBClient object

### ISSUE THREAD

**Issue by GabMus** [jath03/openrgb-python#2]
- OS: Arch Linux
- OpenRGB version: `openrgb-git r618.b3cadba-1`
- openrgb-python version: `python-openrgb-git v0.0.5.r1.gf32661a-1` (AUR package I made myself)

<details>
<summary>Full traceback</summary>
<pre>
client = OpenRGBClient()
6 23
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/site-packages/openrgb/network.py", line 61, in listen
    self.callback(device_id, packet_type, utils.ControllerData.unpack(data))
  File "/usr/lib/python3.8/site-packages/openrgb/utils.py", line 428, in unpack
    start, zones = parse_list(ZoneData, data, start)
  File "/usr/lib/python3.8/site-packages/openrgb/utils.py", line 114, in parse_list
    start, thing = kind.unpack(data, start, x)
  File "/usr/lib/python3.8/site-packages/openrgb/utils.py", line 336, in unpack
    matrix[y][x] = struct.unpack("I", data[start:start + struct.calcsize("I")])
IndexError: list assignment index out of range
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/openrgb/orgb.py", line 207, in __init__
    sleep(.2)
</pre>
</details>

**Comment by jath03** [comment]
I have been unable to test this part of the library because I don't have any rgb devices with matrix zones.  Just making sure that that nothing is _really_ wrong, do you have a device with a zone with a 23x6 matrix?

**Comment by GabMus** [comment]
Don't know what a 23x6 matrix could be, maybe a keyboard? It seems to small to be actually 23x6 but I do have a GMMK TKL keyboard.
