### ISSUE TITLE
Getting a socket.timeout everytime on initialization 

### ISSUE THREAD

**Issue by Plutonium-239** [jath03/openrgb-python#34]
Pretty self-explanatory,

```
> from openrgb import OpenRGBClient
> client = OpenRGBClient()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\x\AppData\Local\Programs\Python\Python38\lib\site-packages\openrgb\orgb.py", line 283, in __init__
    self.comms = NetworkClient(self._callback, address, port, name, protocol_version)
  File "C:\Users\x\AppData\Local\Programs\Python\Python38\lib\site-packages\openrgb\network.py", line 42, in __init__
    self.start_connection()
  File "C:\Users\x\AppData\Local\Programs\Python\Python38\lib\site-packages\openrgb\network.py", line 54, in start_connection
    self.sock.connect((self.address, self.port))
socket.timeout: timed out
```

Tried this multiple times on multiple sessions, help?

**Comment by jath03** [comment]
Can you make sure you have the SDK server running?  If so, do you have some kind of special firewall or something?
