### ISSUE TITLE
Issue with brigtness with protocol < 3 ?

### ISSUE THREAD

**Issue by koying** [jath03/openrgb-python#42]
A user of the HA got the following stackdump, with v0.2.10:

```
[139967665461568] '<=' not supported between instances of 'NoneType' and 'NoneType'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
await self.hass.helpers.service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/components/light/init.py", line 462, in async_handle_light_on_service
await light.async_turn_on(**filter_turn_on_params(light, params))
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 895, in async_turn_on
await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/openrgb/light.py", line 162, in turn_on
self._device_turned_on(**kwargs)
File "/config/custom_components/openrgb/light.py", line 286, in _device_turned_on
self._set_effect()
File "/config/custom_components/openrgb/light.py", line 310, in _set_effect
self._light.set_mode(self._effect)
File "/usr/local/lib/python3.9/site-packages/openrgb/orgb.py", line 231, in set_mode
data = mode.pack(self.comms._protocol_version)
File "/usr/local/lib/python3.9/site-packages/openrgb/utils.py", line 276, in pack
self.validate()
File "/usr/local/lib/python3.9/site-packages/openrgb/utils.py", line 256, in validate
assert self.brightness_min <= self.brightness <= self.brightness_max
TypeError: '<=' not supported between instances of 'NoneType' and 'NoneType'
```

I suspect it is due to the ORGB protocol 3 support? 
brightness_min / brightness_max seems to be None otherwise...

**Comment by koying** [comment]
I can't reproduce on my side though...
The user told he was on 0.6, while I'm only on 0.51
