### ISSUE TITLE
Newbie question/error: ImportError: cannot import name 'OpenRGBClient' from partially initialized module 'openrgb' (most likely due to a circular import) 

### ISSUE THREAD

**Issue by Calimerorulez** [jath03/openrgb-python#52]
Hi,

Just experimenting with Python, I'm trying to get the module working, but I'm getting the following error when running the sample code below:

```
from openrgb import OpenRGBClient
cli = OpenRGBClient()
```

```
root@charon:~# python3 openrgb.py 
Traceback (most recent call last):
  File "/root/openrgb.py", line 1, in <module>
    from openrgb import OpenRGBClient
  File "/root/openrgb.py", line 1, in <module>
    from openrgb import OpenRGBClient
ImportError: cannot import name 'OpenRGBClient' from partially initialized module 'openrgb' (most likely due to a circular import) (/root/openrgb.py)
```

Can you please point me in the right direction?

**Comment by Calimerorulez** [comment]
Thank you very much for pointing that out!
