### ISSUE TITLE
IndexError on connection

### ISSUE THREAD

**Issue by Deinara** [jath03/openrgb-python#53]
Operating system: Manjaro
Python version: 3.10.2
OpenRGB version: 0.7 (appimage)
python-openrgb: 0.0.5-1

Hi, 

While trying to connect to my local OpenRGB server, I get the following error:
```
$ python test.py 
7 23
Exception in thread Thread-1 (listen):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/site-packages/openrgb/network.py", line 61, in listen
    self.callback(device_id, packet_type, utils.ControllerData.unpack(data))
  File "/usr/lib/python3.10/site-packages/openrgb/utils.py", line 428, in unpack
    start, zones = parse_list(ZoneData, data, start)
  File "/usr/lib/python3.10/site-packages/openrgb/utils.py", line 114, in parse_list
    start, thing = kind.unpack(data, start, x)
  File "/usr/lib/python3.10/site-packages/openrgb/utils.py", line 336, in unpack
    matrix[y][x] = struct.unpack("I", data[start:start + struct.calcsize("I")])
IndexError: list assignment index out of range
```
My python file contains just the following:
```
from openrgb import OpenRGBClient

cli = OpenRGBClient('localhost', 6742)
```
Do you have a clue what could be going on?
Thanks!

----
p.s. "But those are the defaults" you might say.
I know, I didn't change any settings for the OpenRGB server, but with
```
from openrgb import OpenRGBClient

cli = OpenRGBClient()
```
I get
```
$ python test.py 
Traceback (most recent call last):
  File "/home/christiaan/python_openrgb/test.py", line 3, in <module>
    cli = OpenRGBClient()
  File "/usr/lib/python3.10/site-packages/openrgb/orgb.py", line 197, in __init__
    self.comms = NetworkClient(self._callback, address, port, name)
  File "/usr/lib/python3.10/site-packages/openrgb/network.py", line 23, in __init__
    self.sock.connect((address, port))
ConnectionRefusedError: [Errno 111] Connection refused
```
----

```
openrgb -l
Attempting to connect to local OpenRGB server.
Connected to server
Network client listener started
Client: Received controller count from server: 4
Client: Requesting controller 0
Client: Requesting controller 1
Client: Requesting controller 2
Client: Requesting controller 3
Client: All controllers received, adding them to master list
Local OpenRGB server connected, running in client mode
0: Corsair Vengeance Pro RGB
  Type:           DRAM
  Description:    Corsair Vengeance Pro RGB Device
  Location:       I2C: /dev/i2c-0, address 0x5A
  Modes: [Direct] Static 'Color Shift' 'Color Pulse' 'Rainbow Wave' 'Color Wave' Visor Rain Marquee Rainbow Sequential
  Zones: 'Corsair Pro Zone'
  LEDs: 'Corsair Pro LED 0' 'Corsair Pro LED 1' 'Corsair Pro LED 2' 'Corsair Pro LED 3' 'Corsair Pro LED 4' 'Corsair Pro LED 5' 'Corsair Pro LED 6' 'Corsair Pro LED 7' 'Corsair Pro LED 8' 'Corsair Pro LED 9'

1: Corsair Vengeance Pro RGB
  Type:           DRAM
  Description:    Corsair Vengeance Pro RGB Device
  Location:       I2C: /dev/i2c-0, address 0x5B
  Modes: [Direct] Static 'Color Shift' 'Color Pulse' 'Rainbow Wave' 'Color Wave' Visor Rain Marquee Rainbow Sequential
  Zones: 'Corsair Pro Zone'
  LEDs: 'Corsair Pro LED 0' 'Corsair Pro LED 1' 'Corsair Pro LED 2' 'Corsair Pro LED 3' 'Corsair Pro LED 4' 'Corsair Pro LED 5' 'Corsair Pro LED 6' 'Corsair Pro LED 7' 'Corsair Pro LED 8' 'Corsair Pro LED 9'

2: B550M AORUS ELITE
  Type:           Motherboard
  Description:    IT5702-GIGABYTE V2.0.10.0
  Version:        0x000A0002
  Location:       HID: /dev/hidraw0
  Serial:         0x57020100
  Modes: [Direct] Static Breathing Blinking 'Color Cycle' Flashing
  Zones: 'D_LED1 Bottom' 'D_LED2 Top' Motherboard
  LEDs: 'Name for LED Strip 1 LED 0' 'Name for LED Strip 1 LED 1' 'Name for LED Strip 1 LED 2' 'Name for LED Strip 1 LED 3' 'Name for LED Strip 1 LED 4' 'Name for LED Strip 1 LED 5' 'Name for LED Strip 1 LED 6' 'Name for LED Strip 1 LED 7' 'Name for LED Strip 2 LED 0' 'Name for LED Strip 2 LED 1' 'Name for LED Strip 2 LED 2' 'Name for LED Strip 2 LED 3' 'Name for LED Strip 2 LED 4' 'Name for LED Strip 2 LED 5' 'Name for LED Strip 2 LED 6' 'Name for LED Strip 2 LED 7' 'Name for Led 1' 'Name for Led 2' 'Name for Led 3' 'Name for Led 4' 'Name for Led 5' 'Name for Led 6' 'Name for Led 7' 'Name for Led 8'

3: Corsair K70 RGB MK.2
  Type:           Keyboard
  Description:    Corsair RGB Peripheral Device
  Version:        3.36
  Location:       HID: /dev/hidraw2
  Serial:         1401D017AF1584275961890EF5001BC5
  Modes: [Direct]
  Zones: Keyboard
  LEDs: 'Key: Escape' 'Key: `' 'Key: Tab' 'Key: Caps Lock' 'Key: Left Shift' 'Key: Left Control' 'Key: F12' 'Key: =' 'Key: Lock' 'Key: Number Pad 7' 'Key: F1' 'Key: 1' 'Key: Q' 'Key: A' 'Key: Left Windows' 'Key: Print Screen' 'Key: Media Mute' 'Key: Number Pad 8' 'Key: F2' 'Key: 2' 'Key: W' 'Key: S' 'Key: Z' 'Key: Left Alt' 'Key: Scroll Lock' 'Key: Backspace' 'Key: Media Stop' 'Key: Number Pad 9' 'Key: F3' 'Key: 3' 'Key: E' 'Key: D' 'Key: X' 'Key: Pause/Break' 'Key: Delete' 'Key: Media Previous' 'Key: F4' 'Key: 4' 'Key: R' 'Key: F' 'Key: C' 'Key: Space' 'Key: Insert' 'Key: End' 'Key: Media Play/Pause' 'Key: Number Pad 4' 'Key: F5' 'Key: 5' 'Key: T' 'Key: G' 'Key: V' 'Key: Home' 'Key: Page Down' 'Key: Media Next' 'Key: Number Pad 5' 'Key: F6' 'Key: 6' 'Key: Y' 'Key: H' 'Key: B' 'Key: Page Up' 'Key: Right Shift' 'Key: Num Lock' 'Key: Number Pad 6' 'Key: F7' 'Key: 7' 'Key: U' 'Key: J' 'Key: N' 'Key: Right Alt' 'Key: ]' 'Key: Right Control' 'Key: Number Pad /' 'Key: Number Pad 1' 'Key: F8' 'Key: 8' 'Key: I' 'Key: K' 'Key: M' 'Key: Right Windows' 'Key: \ (ANSI)' 'Key: Up Arrow' 'Key: Number Pad *' 'Key: Number Pad 2' 'Key: F9' 'Key: 9' 'Key: O' 'Key: L' 'Key: ,' 'Key: Menu' 'Key: Left Arrow' 'Key: Number Pad -' 'Key: Number Pad 3' 'Key: F10' 'Key: 0' 'Key: P' 'Key: ;' 'Key: .' 'Key: Enter' 'Key: Down Arrow' 'Key: Number Pad +' 'Key: Number Pad 0' 'Key: F11' 'Key: -' 'Key: [' 'Key: '' 'Key: /' 'Key: Brightness' 'Key: Right Arrow' 'Key: Number Pad Enter' 'Key: Number Pad .' 'Key: / (ISO)' 'Key: \ (ISO)' 'Key: Logo Left' 'Key: Logo Right' 'Key: Profile'
```

**Comment by jath03** [comment]
The `python-openrgb` package from the AUR is way out of date.  Try the `python-openrgb-git` package instead.

**Comment by Deinara** [comment]
Oh, I see. Yep, that instantly resolved both issues. Thanks!
