### ISSUE TITLE
ValueError when creating an OpenRGBClient object (Windows 10)

### ISSUE THREAD

**Issue by cameronshinn** [jath03/openrgb-python#8]
Running the example file, I get the following exception:
```
Traceback (most recent call last):
  File ".\openrgb_test.py", line 4, in <module>
    client = OpenRGBClient()
  File "C:\Users\Cameron\AppData\Local\Programs\Python\Python38-32\lib\site-packages\openrgb\orgb.py", line 234, in __init__
    self.comms.requestDeviceNum()
  File "C:\Users\Cameron\AppData\Local\Programs\Python\Python38-32\lib\site-packages\openrgb\network.py", line 123, in requestDeviceNum
    self.read()
  File "C:\Users\Cameron\AppData\Local\Programs\Python\Python38-32\lib\site-packages\openrgb\network.py", line 94, in read
    self.callback(device_id, packet_type, buff[0])
  File "C:\Users\Cameron\AppData\Local\Programs\Python\Python38-32\lib\site-packages\openrgb\orgb.py", line 247, in _callback
    self.comms.requestDeviceData(x)
  File "C:\Users\Cameron\AppData\Local\Programs\Python\Python38-32\lib\site-packages\openrgb\network.py", line 116, in requestDeviceData
    self.read()
  File "C:\Users\Cameron\AppData\Local\Programs\Python\Python38-32\lib\site-packages\openrgb\network.py", line 105, in read
    self.callback(device_id, packet_type, utils.ControllerData.unpack(data))
  File "C:\Users\Cameron\AppData\Local\Programs\Python\Python38-32\lib\site-packages\openrgb\utils.py", line 443, in unpack
    start, mode = ModeData.unpack(data, start, x)
  File "C:\Users\Cameron\AppData\Local\Programs\Python\Python38-32\lib\site-packages\openrgb\utils.py", line 279, in unpack
    buff[8] = ModeColors(buff[8])
  File "C:\Users\Cameron\AppData\Local\Programs\Python\Python38-32\lib\enum.py", line 309, in __call__
    return cls.__new__(cls, value)
  File "C:\Users\Cameron\AppData\Local\Programs\Python\Python38-32\lib\enum.py", line 600, in __new__
    raise exc
  File "C:\Users\Cameron\AppData\Local\Programs\Python\Python38-32\lib\enum.py", line 584, in __new__
    result = cls._missing_(value)
  File "C:\Users\Cameron\AppData\Local\Programs\Python\Python38-32\lib\enum.py", line 613, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 262144 is not a valid ModeColors
```
I assume this value is getting pulled from the SDK.
I am using version 0.2.3 (pip) and am running Python 3.8.5

**Comment by jath03** [comment]
At first glance, this looks like a problem on the server side.  What devices do you have that are supported by openrgb?

**Comment by cameronshinn** [comment]
I have...
* Corsair keyboard
* Razer mouse
* NZXT AIO cooler and Hue+ lighting
* Gigabyte RGB mobo w/ RGB RAM
* Gigabyte GPU

**Comment by Lucasthoelke** [comment]
I'm having the same issue,

Devices:

- Corsair K70 RGB MK.2
- LED Strip
- Logitech g502
- NZXT Kraken X2

OpenRGB 0.41 3767b3

**Comment by RelishedChicken** [comment]
Just to add, I'm seeing the same issue when a this is a dependency.

Devices:

- Razer Blackwidow V2 Chroma
- Razer Mamba Wireless Chroma
- Razer Goliathus Extended Chroma
- NZXT Kraken x56
- NZXT N7 Z370 Motherboard (RGB)
- Corsair Vengeance Pro RGB

**Comment by cameronshinn** [comment]
The common factor here seems like the NZXT Kraken cooler

**Comment by jath03** [comment]
Nothing seems wrong with the kraken's implementation in OpenRGB. I'm working on adding good logging to get more info and make debugging easier.

**Comment by jath03** [comment]
Sorry I haven't gotten around to adding logging yet.  From discussion on discord though, it seems like this error is a symptom of SDK connection issues, which are mostly caused by trying to request device info to quickly or in parallel.  If you're using multiprocessing, don't.  The library is thread-safe, but not multiprocessing-safe, so feel free to replace all multiprocessing with threading.  I'll add a section in the docs about this.  If this fixes any of your problems, great, otherwise I'll try to make time to add logging

**Comment by inlart** [comment]
I think PR #11 should fix this. Could you give the latest git version a try? Alternatively you can also update OpenRGB to [23460959](https://gitlab.com/CalcProgrammer1/OpenRGB/-/commit/234609599491603c1e09f9e4f2a00815fdc18e79) or newer.

**Comment by jath03** [comment]
The latest release added some fixes and locking that should (hopefully) help with network stability.  Could you lmk if it does or doesn't help at all?  Which example are you running when you get this error.

**Comment by cameronshinn** [comment]
Yeah I can run it when I get the chance

**Comment by jath03** [comment]
Can anyone here verify that this issue is still occurring?
